version: "3"

services:
  docker-mysql:
    image: mysql:8
    container_name: docker-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=docker_shop
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=root123
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - /dbdata:/var/lib/mysql

  docker-nginx:
    container_name: docker-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ../:/var/www:rw
    depends_on:
      - docker-php-fpm
      - docker-mysql

  docker-php-fpm:
    container_name: docker-php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    volumes:
      - /var/www/vendor/
      - ./../:/var/www/

volumes:
  db_data: